export const NAVIGATE = 'NAVIGATE';
export const SET_APP_MODE = 'SET_APP_MODE';
export const UPDATE_CONFIG = 'UPDATE_CONFIG';
export const SET_SETUP_MODE = 'SET_SETUP_MODE';
export const SET_EDITING_PINNED_ID = 'SET_EDITING_PINNED_ID';
export const SET_RESULTS = 'SET_RESULTS';
export const SET_SCORE_ANIM = 'SET_SCORE_ANIM';
export const SET_HIST_FILTER = 'SET_HIST_FILTER';
export const SET_LEARN_FILTER = 'SET_LEARN_FILTER';
export const SET_SELECTED_ARTICLE = 'SET_SELECTED_ARTICLE';
export const SET_SELECTED_SESSION = 'SET_SELECTED_SESSION';
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';

export const BLE_CONNECTING = 'BLE_CONNECTING';
export const BLE_CONNECTED = 'BLE_CONNECTED';
export const BLE_DISCONNECTED = 'BLE_DISCONNECTED';
export const BLE_ERROR = 'BLE_ERROR';

export const SET_GUIDE_MEDIA = 'SET_GUIDE_MEDIA';
export const CLEAR_GUIDE_MEDIA = 'CLEAR_GUIDE_MEDIA';

export const ADD_PINNED_SESSION = 'ADD_PINNED_SESSION';
export const UPDATE_PINNED_SESSION = 'UPDATE_PINNED_SESSION';
export const REMOVE_PINNED_SESSION = 'REMOVE_PINNED_SESSION';

export const RECORD_COMPLETED_SESSION = 'RECORD_COMPLETED_SESSION';
export const ADD_SESSION = 'ADD_SESSION';
export const UPDATE_SESSION = 'UPDATE_SESSION';

export const ADD_CUSTOM_TEMPLATE = 'ADD_CUSTOM_TEMPLATE';
export const UPDATE_NEW_CUSTOM_TYPE = 'UPDATE_NEW_CUSTOM_TYPE';
export const RESET_NEW_CUSTOM_TYPE = 'RESET_NEW_CUSTOM_TYPE';

export const RESTORE_STATE = 'RESTORE_STATE';
export const RESET_TO_MODE = 'RESET_TO_MODE';
